// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3I_qRDKnh0cyHCBc0CJ9UNjKfq5ZXgLM',
    appId: '1:282275414352:web:3d33676d294324d8bdac55',
    messagingSenderId: '282275414352',
    projectId: 'carwash-a54fc',
    authDomain: 'carwash-a54fc.firebaseapp.com',
    storageBucket: 'carwash-a54fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeAiMN8d6zQYCiDYnlKt2Bw3l7bwtF8ro',
    appId: '1:282275414352:android:990efcee92bc6276bdac55',
    messagingSenderId: '282275414352',
    projectId: 'carwash-a54fc',
    storageBucket: 'carwash-a54fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAooBjubvMIroAwBV2xQ3JZW8dbnKRnU0k',
    appId: '1:282275414352:ios:39f312c590eb1f0dbdac55',
    messagingSenderId: '282275414352',
    projectId: 'carwash-a54fc',
    storageBucket: 'carwash-a54fc.appspot.com',
    iosBundleId: 'com.example.carwash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAooBjubvMIroAwBV2xQ3JZW8dbnKRnU0k',
    appId: '1:282275414352:ios:39f312c590eb1f0dbdac55',
    messagingSenderId: '282275414352',
    projectId: 'carwash-a54fc',
    storageBucket: 'carwash-a54fc.appspot.com',
    iosBundleId: 'com.example.carwash',
  );
}
